### ISSUE TITLE
[Bug] Incorrect ("data missing") message shown when cloud data is loading

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/features-bugs#2]
### Kubecost Version

1.106.2

### Kubernetes Version

n/a

### Kubernetes Platform

Other (specify in description)

### Description

Incorrectly seeing this message when I request a long when, data does eventually load: https://infra.kceng.dev/cloud?reportTitle=Cumulative+cost+for+last+12+months+by+provider&window=365d&agg=provider

<img width="1520" alt="image" src="https://github.com/kubecost/features-bugs/assets/298359/1d324bea-0e11-450d-8ebc-9851bef86049">

### Steps to reproduce

Load this view: https://infra.kceng.dev/cloud?reportTitle=Cumulative+cost+for+last+12+months+by+provider&window=365d&agg=provider

### Expected behavior

Expect a loading state, but instead shows a data not available message

### Troubleshooting

- [X] I have read and followed the [issue guidelines](ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
@nealormsbee I'm relearning our process but any chance you can help review/triage?!

**Comment by nealormsbee** [comment]
Sure thing! This definitely looks like a state issue in our UI. The process here _should_ be for eng to replicate this ticket in Jira for internal tracking, schedule the fix, and update here when we release an update resolving the issue.

**Comment by dwbrown2** [comment]
Sg! @kwombach12 @chipzoller are we ok with internal Jira tickets being referenced in these GH threads? I personally think it's valuable to cross-link them.

**Comment by chipzoller** [comment]
> are we ok with internal Jira tickets being referenced in these GH threads?

I think in this repo it's fine to do.

> The process here should be for eng to replicate this ticket in Jira for internal tracking, schedule the fix, and update here when we release an update resolving the issue.

Agree, this should be the process. The danger here is when Jira gets closed but this doesn't, now we fall back into the situation where one repo has a bunch of stale or no longer applicable entries which makes triaging and product management more difficult. That's why I think if we're going to have two sources of truth rather than one, we need some automated integration so that, minimally, closure of the Jira issue as a result of a release process closes an issue in GitHub.

**Comment by nealormsbee** [comment]
This ^

While we're not there today, automation is the dream. I think it makes sense to close the public-facing versions of issues not when the code is merged, but when the release with the fix is published.

Even a manual process would be ok as an intermediate step, IMO. We could start by flagging items in Jira with corresponding GH issues, and then after a release, we go through closed Jira issues with a linked GH issue and update them.

**Comment by nealormsbee** [comment]
Jira issue: https://kubecost.atlassian.net/browse/SELFHOST-828

Labeled with label `GH_Linked` so we can search it as an issue with a corresponding public item. @cliffcolvin let's have a discussion around a proper scheme for this when we can (assuming you're on board with the whole concept).

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
