### ISSUE TITLE
[Bug] Cloud Costs from CUR is not exposed by prometheus

### ISSUE THREAD

**Issue by salvadoriume** [kubecost/features-bugs#55]
### Kubecost Version

2.0.2

### Kubernetes Version

1.25

### Kubernetes Platform

EKS

### Description

I added integration with CUR, kubecost properly show data from CUR in kubecost dashboard UI.
When I go to grafana and check prometheus metrics only metrics from inside kubernetes are exposed.

### Steps to reproduce

1. add CUR integration - so data is visible in UI
2. check grafana/prometheus for metrics for CloudCosts 

### Expected behavior

Visible cloud costs (s3, ec2.. all data from CUR) in exposed prometheus metrics

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
@salvadoriume we actually used to expose cloud costs metrics in Prom but due to cardinality we rethought this approach. If we're going to do this I think it should be done in the underlying open source project [OpenCost](https://github.com/opencost/opencost). Have any more details on your specific use? For example, are you just looking for service level & account-level costs or would you want more metadata?

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
